const double LEFT_BANNER_WIDTH = 20.0;
const double DRAWER_WIDTH = 300.0;

const double TITLE_MARGIN = 16.0;

const double TITLE_FONT_SIZE = 30.0;

const double FRAME_LEFT_RATIO = 375;
const double FRAME_TOP_RATIO = 221;
const double FRAME_RIGHT_RATIO = 1144;
const double FRAME_BOTTOM_RATIO = 650;

const double BOTTOM_ACTION_BAR_HEIGHT = 60.0;
const double BOTTOM_ACTION_BAR_CORNER_RADIUS = 12.0;
const double BOTTOM_ACTION_BAR_COLOR_BUTTON_WIDTH = 50.0;
const double BOTTOM_ACTION_BAR_COLOR_CIRCLE_SIZE = 26.0;
const double BOTTOM_ACTION_BAR_COLOR_CIRCLE_BORDER_WIDTH = 3.0;